apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-app
    app.kubernetes.io/name: node-backend
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
      tier: node-backend
  template:
    metadata:
      labels:
        app: my-app
        tier: node-backend
    spec:
      containers:
        - image: khanzuber911/backend
          name: node-app-backend
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: node-backend
  name: backend
spec:
  selector:
    app: my-app
    tier: node-backend
  ports:
   -  protocol: TCP
      port: 8000
      targetPort: 8000
